public void invoke(){
	try{
		TestExceptionHandler.runTry();
	}
	catch(Exception local$1){
		TestExceptionHandler.runCatch();
	}
}